### actors Index

GET http://localhost:3000/actors

### actors Show

GET http://localhost:3000/actors/8

### actors create

POST http://localhost:3000/actors
Content-Type: application/json

{
  "first_name": "T",
  "last_name": "Data",
  "known_for": "Test Data",
  "gender": "male",
  "age": "6"
}

### actors Update

PATCH http://localhost:3000/actors/8
Content-Type: application/json

{
  "known_for": "update"
}

### actors Delete

DELETE http://localhost:3000/actors/15

### movies Index

GET http://localhost:3000/movies

### movies Show

GET http://localhost:3000/movies/8

### movies create

POST http://localhost:3000/movies
Content-Type: application/json

{
  "title": "Test",
  "year": "so",
  "plot": "Data",
  "director": "Test",
  "english": "true"
}

### movies Update

PATCH http://localhost:3000/movies/1
Content-Type: application/json

{
  "english": "false"
}

### movies Delete

DELETE http://localhost:3000/movies/11