### actors Index

#admin
@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTgwMzMyNzd9.M-Ydl_gDN3dPndowXy-arz1TgJZ09FrsCjYTrtIl67o

#user
# @jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NTgwMzMzODB9.49e-LJX664eI0Vjc57UEr0j9krb-mDZPoAixaE339WQ

GET http://localhost:3000/actors

### actors Show

GET http://localhost:3000/actors/8

### actors create

POST http://localhost:3000/actors
Content-Type: application/json

{
  "first_name": "T",
  "last_name": "Data",
  "known_for": "Test Data",
  "gender": "male",
  "age": "6"
}

### actors Update

PATCH http://localhost:3000/actors/8
Content-Type: application/json

{
  "known_for": "update"
}

### actors Delete

DELETE http://localhost:3000/actors/15

### movies Index

GET http://localhost:3000/movies

### movies Show

GET http://localhost:3000/movies/8

### movies create

POST http://localhost:3000/movies
Content-Type: application/json

{
  "title": "Test",
  "year": "so",
  "plot": "Data",
  "director": "Test",
  "english": "true"
}

### movies Update

PATCH http://localhost:3000/movies/1
Content-Type: application/json

{
  "english": "false"
}

### movies Delete

DELETE http://localhost:3000/movies/11

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test name3",
  "email": "test3@test.com",
  "admin": "false",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test2@test.com",
  "password": "password"
}